language:
 - cpp

os:
 - linux
dist: trusty
sudo: required
compiler:
     - clang

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  
  packages:
   - gcc-5
   - g++-5
   - build-essential
   - cmake
   - git
   - rpm
   - libgtk2.0-dev
   - pkg-config
   - libavcodec-dev
   - libavformat-dev
   - libswscale-dev
   - python-dev
   - python-numpy
   - libtbb2
   - libtbb-dev
   - libjpeg-dev
   - libpng-dev
   - libtiff-dev
   - libjasper-dev
   - libdc1394-22-dev
   - libboost-all-dev
   - libmysqlclient-dev
   - libmongo-client-dev
   - lcov

install:
 - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
         sudo apt-get update -qq
      && sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev qttools5-dev libqt5webkit5-dev
      ;
   else
         brew tap homebrew/science
      && brew update
      && brew install cmake
      && brew install qt5
      && brew install opencv3 --with-contrib
      ;
   fi

before_script:
 - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
 - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
 - gcc -v
 - g++ -v

 - wget http://www.cmake.org/files/v3.6/cmake-3.6.0.tar.gz
 - tar xf cmake-3.6.0.tar.gz
 - cd cmake-3.6.0
 - ./configure
 - make
 - sudo make install
 - cd ..

 - git clone https://github.com/opencv/opencv
 - cd opencv
 - mkdir -p build
 - cd build
 - cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=RELEASE -DWITH_FFMPEG=OFF -DWITH_IPP=OFF ..
 - make -j8
 - sudo make install
 - cd ../../

 - git clone https://github.com/pocoproject/poco
 - sed -i 's#mysqlclient_r#mysqlclient mysqlclient_r#g' poco/cmake/FindMySQL.cmake
 - cd poco
 - mkdir -p build
 - cd build
 - cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Release .. && make -j3 && sudo make install && sudo ldconfig
 - cd ../..

 - git clone https://github.com/davisking/dlib
 - cd dlib
 - mkdir build; cd build; cmake -DCMAKE_CXX_COMPILER=$CXX .. ; make; sudo make install
 - cd ../../

 - git clone https://github.com/annotatorproject/annotatorlib
 - cd annotatorlib
 - git submodule update --init --recursive
 - mkdir build
 - cd build
 - cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DPoco_DIR=../../poco/build/Poco -DOpenCV_DIR=../../opencv/build -DOPTION_BUILD_TESTS=0 -DOPTION_BUILD_PYTHON=0 ..
 - make
 - cd ../../

 - mkdir build
 - cd build
 - cmake -DCMAKE_CXX_COMPILER=$CXX -Dannotatorlib_DIR=annotatorlib -DPoco_DIR=poco/build/Poco -DOpenCV_DIR=opencv/build -DCMAKE_BUILD_TYPE=Release -DOPTION_BUILD_TESTS=0 ..
script:
 - make -j4
 - make pack

after_success:
  - make snap
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file:
   - $TRAVIS_BUILD_DIR/build/*.deb
   - $TRAVIS_BUILD_DIR/build/*.rpm
  skip_cleanup: true
  on:
    tags: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aeb39f01907f575253df
    on_success: change
    on_failure: always
    on_start: never
